### ISSUE TITLE
Examples results in 404 due to bad url

### ISSUE THREAD

**Issue by trek2710** [F5EMEA/oltra#11]
This page:
https://github.com/F5EMEA/oltra/tree/main/use-cases/cis-examples/cis-crd#virtualserver-crd-examples
have all the links pointing incorrectly eg
[wrong] https://github.com/F5EMEA/oltra/blob/main/use-cases/cis-examples/cis-crd/cis-crd/VirtualServer/Basic
instead of
[right] https://github.com/F5EMEA/oltra/blob/main/use-cases/cis-examples/cis-crd/VirtualServer/Basic

**cis-crd is duplicated in all the links**

**Comment by skenderidis** [comment]
Thanks for the pull request. I merged it
